### ISSUE TITLE
링띤 링크 정상작동을 전수조사

### ISSUE THREAD

**Issue by roeniss** [AUSG/2022-homepage#11]
링띤 링크가 본인이 커스텀 안하면 랜덤해시값이 디폴트일거임. 이 부분 인지 못한 분이 더 있을 수 있음

**Comment by naru200** [comment]
랜덤해시가 디폴트라구요....? ㄹㅇ....?

**Comment by naru200** [comment]
아 랜덤해시가 디폴트값인건 맞을텐데 그게 시간에 따라 바뀌진 않을거에요

**Comment by naru200** [comment]
정상작동 안하는 케이스는 아마 기본값에서 커스텀한값으로 바꾸신분들 아닐까...싶습니다

**Comment by roeniss** [comment]
시간에 따라 바뀐다곤 안했는데 ㅜ.ㅜ

**Comment by roeniss** [comment]
마이그레이션 누가했냐?

- 길재은

**Comment by roeniss** [comment]
마이그레이션 누가했냐?
